# ─────────────────────────────────────────────────
#  sonar-project.properties  —  Java / Maven
#
#  WHERE TO PUT THIS FILE:
#    Root of your Java app repo
#    (same folder as pom.xml)
#
#  WHAT TO CHANGE:
#    sonar.projectKey   ← must match what you created in SonarQube UI
#    sonar.projectName  ← display name shown in SonarQube dashboard
#
#  NOTE:
#    For Maven projects you can also run analysis without this file:
#    mvn sonar:sonar -Dsonar.projectKey=my-app
# ─────────────────────────────────────────────────

sonar.projectKey=my-java-app              # ← CHANGE THIS
sonar.projectName=My Java App             # ← CHANGE THIS
sonar.projectVersion=1.0

# Source code location
sonar.sources=src/main/java
sonar.tests=src/test/java

# Compiled class files (Maven puts them here)
sonar.java.binaries=target/classes

# Test coverage report (generated by JaCoCo plugin)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclude these from analysis
sonar.exclusions=**/generated/**,**/*Test.java
